spring:
  application:
    name: web
  datasource:
    url: jdbc:ydb:grpc://localhost:2136/local
    driver-class-name: tech.ydb.jdbc.YdbDriver
  jpa:
    properties:
      hibernate:
        dialect: tech.ydb.hibernate.dialect.YdbDialect
