spring:
  application:
    name: web
  datasource:
    url: jdbc:ydb:${YDB_URL:grpc://localhost:2136/local}
    driver-class-name: tech.ydb.jdbc.YdbDriver
  jpa:
    properties:
      hibernate:
        dialect: tech.ydb.hibernate.dialect.YdbDialect
    hibernate:
      ddl-auto: update

IS_CLOUD_ENV: ${IS_PROD:false}

gg:
  jte:
    development-mode: false
    template-location: src/main/jte
    template-suffix: .jte
    use-precompiled-templates: true
